### ISSUE TITLE
Verify GH org?

### ISSUE THREAD

**Issue by maelle** [r-hub/devops-issues#28]
https://blog.github.com/changelog/2018-08-07-domain-verification/

**Comment by maelle** [comment]
But you'd need a domain first :-)

**Comment by maelle** [comment]
Is it something dependent on IT?

**Comment by gaborcsardi** [comment]
I think so, but I can tell them... what do they need to do for this?

**Comment by maelle** [comment]
According to https://help.github.com/en/articles/verifying-your-organizations-domain

"To verify domains on GitHub, you must have owner permissions in the organization. (...)You will also need access to modify domain records with your domain hosting service." which is a combo no one has for R-hub but I guess it can work anyway if you start the process and then tell IT how to " create a DNS TXT record with your domain hosting service." and then it'd be back to you for "After confirming your TXT record is added to your DNS, navigate to the Verified domains tab in your organization's settings. " and back to them to delete the TXT record if they want to (that last step is optional).

**Comment by gaborcsardi** [comment]
OK, asked them.

**Comment by maelle** [comment]
:crossed_fingers:

**Comment by gaborcsardi** [comment]
This is done, I believe.

**Comment by maelle** [comment]
Then why doesn't it show up on https://github.com/r-hub?

**Comment by gaborcsardi** [comment]
IT does show up here: https://github.com/organizations/r-hub/settings/domains

**Comment by gaborcsardi** [comment]
It seems like we would need to verify builder.r-hub.io as well.

But it would be better to redirect r-hub.io to  builder.r-hub.io....

**Comment by maelle** [comment]
yes the redirection seems like a good thing for now but later it could be a fancier landing page pointing to different services?

**Comment by gaborcsardi** [comment]
OK, set up the redirect. Luckily, this is not from the DNS, so I can change it quickly.
