### ISSUE TITLE
Dashboard of issues

### ISSUE THREAD

**Issue by maelle** [r-hub/devops-issues#36]
Now that the about page of the builder says to write issues in the R package repo, it can mean that if I say see an issue that belongs to another repo, I could miss a duplicate issue in the R package repo. It nearly happened a minute ago hence my wondering.

I know you @gaborcsardi already sort issues across repos by using a GitHub project, so it might be too much to also create a dashboard like the tidyversedashboard (well creating it shouldn't be too much hassle with Jim's package) to help searching for similar issues before creating one (and to link it from the about page). 🤔

**Comment by gaborcsardi** [comment]
Well, I am not going to do this, mainly two reasons. I don't need it myself, pretty much all open issues are in the GH project. Also, I don't want to run a host for it.

**Comment by maelle** [comment]
👍
